### ISSUE TITLE
metalsmith-jade + metalsmith-i18n

### ISSUE THREAD

**Issue by azappa** [doup/metalsmith-i18n#2]
Is there a way to use metalsmith-jade with metalsmith-i18n?

**Comment by doup** [comment]
I've tested it with [`metalsmith-templates`](https://github.com/segmentio/metalsmith-templates) (which, by the way, supports Jade). The method is added to the file object, so I think it should work. Have you tried just calling `__()` in your template?

``` jade
p= __('hello')
p #{__('hello')}
```

**Comment by azappa** [comment]
Could you provide me the metalsmith-templates and metalsmith-i18n config part in your metalsmith.json? or the build.js file (the one you launch with node)?

Both of your examples give me an `undefined is not a function` error (using metalsmith-jade because metalsmith-templates is deprecated now).

Thank you!

**Comment by doup** [comment]
That deprecation is really recent, try with `metalsmith-layouts`. Seems like that should work.
- Try with `metalsmith-layouts` + `jade` (not `metalsmith-jade`)
- Add i18n: https://github.com/grautonomia/web/blob/master/build.js#L164
- Add layouts: https://github.com/grautonomia/web/blob/master/build.js#L191
