### ISSUE TITLE
Handlebars usage example

### ISSUE THREAD

**Issue by marchenko1985** [doup/metalsmith-i18n#3]
Metalsmith by default (at least in examples) uses handlebars.

Will be nice if there will be usage example for handlebars in readme.

**Comment by JimmyMultani** [comment]
@doup Would it be possible to get an example of this please? Thanks!

**Comment by doup** [comment]
The problem is that it doesn't work on Handlebars or that the documentation is missing?

I haven't tested it on HB, I supposed that `metalsmith-layout` (consolidate.js) was exposing the property functions that [`metalsmith-i18n`](https://github.com/doup/metalsmith-i18n/blob/master/lib/index.js#L51) was defining.

**Comment by frankrousseau** [comment]
@doup both. It doesn't look to work with `handlebars` or `mustache`. What is weird is that `mustache` is compatible with `i18n`.

**Comment by frankrousseau** [comment]
I put here the code of my template:

```
---
layout: layout.html
locale: en
---
<h1>{{#__n}}main title{{/__n}}</p>
<h1>{{#__}}main title{{/__}}</p>
<h1>{{__n('main title')}}</p>
<h1>{{main title}}</p>
```

I use the following configuration:

``` javascript
var metalsmith = new Metalsmith(__dirname)
  .use(filenames)
  .use(date)
  .use(stylus())
  .use(asset({
    src: 'assets'
  }))
  .use(i18n({
    default: 'en',
    locales: ['en', 'fr'],
    directory: 'src/locales'
  }))
  .use(layouts({
    engine: "mustache",
    directory: "src/layouts"
  }))
  .build((err) => {
    if (err) throw err
  });
```

And the output is:

```
<h1>{{#__n}}main title{{/__n}}</p>
<h1>{{#__}}main title{{/__}}</p>
<h1>{{__n('main title')}}</p>
<h1>{{main title}}</p>
```

**Comment by frankrousseau** [comment]
Here is the snippet from `i18n` that inspired these syntaxes: https://gist.github.com/mashpie/5247373#file-index-html-L6

**Comment by frankrousseau** [comment]
Do you see what I did wrong?

**Comment by doup** [comment]
@frankrousseau I've been looking into this, so far this is what I know:
- You should be using `metalsmith-in-place` if you want the contents of your files to be processed by the template engine of your choice. `metalsmith-layout` just wraps the contents with a layout. Probably you'll want to use both plugins.
- It seems that when working with `Handlebars` `metalsmith-i18n` only works with simple i18n cases. It doesn't accept named arguments or `__n`. If you just want to translate a string, do:
  
  ```
   {{__ 'i18n_key'}}
  ```
- If you need named arguments, or to change the locale (e.g.: on an english file use a spanish string) you should add a helper that gets this right, this is so far what I've achieved (half-ass implementation, `locale` is not detected…):
  
  ```
  .use(inplace({
      engine: 'handlebars',
      helpers: {
          __: function () {
              var args = Array.prototype.slice.call(arguments, 0, -1);
              var hash = Array.prototype.slice.call(arguments, -1)[0].hash;
  
              args.splice(1, 0, hash);
  
              return this.__.apply(null, args)
          }
      }
  }))
  ```

**Comment by frankrousseau** [comment]
Thank you @doup for the details. I will have a look at this later (on thursday probably) and will provide you with feedback.

**Comment by frankrousseau** [comment]
Ok thank you @doup for that additional information. I made the changes and it now works. I used that configuration:

``` javascript
var metalsmith = new Metalsmith(__dirname)
  .use(filenames)
  .use(ignore([
    "layouts/*",
    "locales/*"
  ]))
  .use(i18n({
    default: 'en',
    locales: ['en', 'fr'],
    directory: 'src/locales'
  }))
  .use(layouts({
    engine: 'handlebars',
    directory: 'src/layouts'
  }))
  .use(inPlace({
    engine: 'handlebars',
    directory: 'src'
  }))
```

Inside the templates, I use the syntax you mention in your comment:

```
 {{__ 'i18n_key'}}
```

The problem is solved. But I have another question :). Do you have any good practice to recommend to automatically generate one website version for each language?

**Comment by doup** [comment]
@frankrousseau check this: https://github.com/doup/metalsmith-multi-language

**Comment by revolunet** [comment]
works great here with 

``` json
{
  "metadata": {
    "title": "xxx.com",
    "description": "MetalSmith powered"
  },
  "plugins": {
    "metalsmith-i18n": {
      "default": "fr",
      "locales": ["en", "fr"],
      "directory": "locales"
    },
    "metalsmith-in-place": {
      "engine": "handlebars",
      "partials": "partials"
    },
    "metalsmith-markdown": {},
    "metalsmith-layouts": {
      "engine": "handlebars"
    },
    "metalsmith-watch": {
      "paths": {
        "src/*": true
      }
    }
  }
}
```
